import { logoutAgency } from "@/modules/auth/actions/agency-auth";
import type { Agency } from "@/db/schema";
import { Icon } from "./agency-portal-primitives";

const nav = ["Overview", "Fleet", "Bookings", "Customers", "Analytics", "Settings"];

export function AgencySidebar({ agency, mobileNav, onClose }: { agency: Agency; mobileNav: boolean; onClose: () => void }) {
  return <aside className={`${mobileNav ? "fixed inset-0 z-30 block bg-white p-5" : "hidden"} lg:static lg:block lg:w-64 lg:shrink-0 lg:border-r lg:border-[#e5e7eb] lg:bg-white lg:p-0`}><div className="flex h-full flex-col lg:sticky lg:top-0 lg:h-screen lg:px-4 lg:py-5"><div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-[#0d9488] text-base font-bold text-white">M</div><div><p className="font-[family-name:var(--font-jakarta)] text-sm font-bold tracking-[-.03em]">MoroccoDrive</p><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#6b7280]">Agency portal</p></div></div><button className="lg:hidden" onClick={onClose} type="button" aria-label="Close navigation"><Icon type="close" /></button></div><nav aria-label="Agency navigation" className="mt-10 space-y-1">{nav.map((label) => <button key={label} className={label === "Fleet" ? "flex w-full items-center gap-3 rounded-md bg-[#e6f5f2] px-3 py-2.5 text-left text-sm font-semibold text-[#0d766e]" : "flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm font-medium text-[#6b7280] transition hover:bg-[#f3f4f6] hover:text-[#111827]"} type="button" onClick={onClose}><Icon type={label === "Fleet" ? "car" : label === "Overview" ? "chart" : label === "Settings" ? "check" : "image"} /><span>{label}</span>{label === "Fleet" && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#0d9488]" />}</button>)}</nav><div className="mt-auto border-t border-[#e5e7eb] px-2 pt-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#6b7280]">Agency account</p><p className="mt-2 truncate text-sm font-semibold">{agency.name}</p><p className="mt-1 text-xs text-[#6b7280]">{agency.city}</p><form action={logoutAgency} className="mt-5"><button type="submit" className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm font-medium text-[#6b7280] transition hover:bg-[#fff2f1] hover:text-[#b42318]"><Icon type="logout" /><span>Sign out</span></button></form></div></div></aside>;
}
