"use client";

import { useState, type ChangeEvent } from "react";
import { deleteVehicleImage, uploadVehicleImages } from "../actions/manage-images";
import type { CarImage } from "../types";

export function VehicleImageManager({ vehicleId, images }: { vehicleId: string; images: CarImage[] }) {
  const [items, setItems] = useState(images); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const files = event.target.files; if (!files?.length) return; const data = new FormData(); Array.from(files).forEach((file) => data.append("images", file)); setBusy(true); setMessage(""); const result = await uploadVehicleImages(vehicleId, data); if (result.success && result.data) setItems((current) => [...current, ...(result.data as CarImage[])]); else setMessage(result.message ?? "The request could not be completed."); setBusy(false); event.target.value = ""; }
  async function remove(id: string) { const result = await deleteVehicleImage(id); if (result.success) setItems((current) => current.filter((image) => image.id !== id)); else setMessage(result.message ?? "The request could not be completed."); }
  return <div className="mt-5 border-t border-slate-100 pt-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{items.length} {items.length === 1 ? "image" : "images"}</p><label className="inline-flex cursor-pointer items-center gap-1.5 rounded-lg bg-teal-50 px-3 py-2 text-xs font-semibold text-teal-700 transition hover:bg-teal-100">{busy ? "Uploading..." : "Add images"}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={upload} className="sr-only" /></label></div>{message && <p className="mt-2 text-xs text-rose-600">{message}</p>}<div className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-4">{items.map((image) => <div key={image.id} className="group relative aspect-[4/3] overflow-hidden rounded-xl bg-slate-100"><img src={image.publicUrl} alt="" className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /><button type="button" onClick={() => remove(image.id)} className="absolute right-1.5 top-1.5 rounded-md bg-slate-950/80 px-1.5 py-0.5 text-sm leading-none text-white opacity-0 transition group-hover:opacity-100 focus:opacity-100" aria-label="Delete image">x</button></div>)}</div></div>;
}
